version: "3.7"
services:
  php:
    build:
      context: backend
      dockerfile: build/Dockerfile
      target: php_runtime
    env_file: .env
    volumes:
      - "./backend:/app"
  nginx:
    build:
      context: frontend
      dockerfile: build/Dockerfile
      target: nginx_runtime
    env_file: .env
    depends_on:
      - php
    volumes:
      - "./frontend:/app"
    ports:
      - "8080:80"
