# Put all your resources under `resources:`. For each resource, you need:
# - The type of resource. In this example, the type is a Compute VM instance.
# - An internal name for the resource.
# - The properties for the resource. In this example, for VM instances, you add
#   the machine type, a boot disk, network information, and so on.
#
# For a list of supported resources,
# see https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types.
resources:
  - type: compute.v1.instance
    name: production
    properties:
      # The properties of the resource depend on the type of resource. For a list
      # of properties, see the API reference for the resource.
      zone: us-central1-a
      machineType: zones/us-central1-a/machineTypes/f1-micro
      tags:
        items:
          - http-server
          - https-server
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            # See a full list of image families at https://cloud.google.com/compute/docs/images#os-compute-support
            sourceImage: projects/cos-cloud/global/images/family/cos-stable
      networkInterfaces:
        - network: global/networks/default
          accessConfigs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
