name: deploy pipeline
on: 
  push:
    branches:
      - master
jobs: 
  build-and-deploy:
    name: Build app and deploy
    runs-on: ubuntu-18.04
    env:
      IMAGES_PROD_NGINX: ${{ secrets.PROD_REPO }}/nginx:${{ github.sha }}
      IMAGES_PROD_PHP: ${{ secrets.PROD_REPO }}/php:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '2.7.1'
      - name: Docker info
        run: docker info
      - name: Build containers
        run: task build
      - name: "Setup gcloud tool"
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '274.0.1'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: GCloud info 
        run: gcloud info
      - name: Select GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_NAME }}
      - name: Config docker to use gcp registry 
        run: gcloud auth configure-docker
      - name: Tag containers to push
        run: |
          docker tag ${DEV_REPO}/php:latest ${IMAGES_PROD_PHP} &&
          docker tag ${DEV_REPO}/nginx:latest ${IMAGES_PROD_NGINX}
        env:
          DEV_REPO: "api-tms" # same as Taskfile.yml vars.IMAGES_BASE_REPOSITORY
      - name: Push containers
        run: |
          docker push ${IMAGES_PROD_PHP} &&
          docker push ${IMAGES_PROD_NGINX}
      - name: Deploy resources
        run: |
          gcloud deployment-manager deployments update production \
            --config deploy/production.yml
      - name: Upload deploy config
        run: gcloud compute --project "mythic-guild-264223" scp
          --zone "us-central1-a"
          docker-compose.yaml production:/home/runner/
      - name: Deploy application
        run: gcloud compute --project "mythic-guild-264223" ssh
          --zone "us-central1-a" "production"
          --command="IMAGES_TAG=${{ github.sha }} REPO=${{ secrets.PROD_REPO }}
            docker stack deploy
            -c /home/runner/docker-compose.yaml
            api-tms-production"
      
