name: deploy pipeline
on: 
  push:
    branches:
      - master
jobs: 
  build-and-deploy:
    name: Build app and deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '2.7.1'
      - name: Build containers
        run: task build
      - name: Login to gcloud
        run: echo "Login here"
      - name: Push containers
        run: echo "Push here"
      - name: Deploy to gcp
        run: echo "deploy to gcp"
      
